"""Add headquarters to contractor

Revision ID: 9b82aaf66885
Revises: 2912e5f2faa8
Create Date: 2026-01-24 03:17:31.821804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b82aaf66885'
down_revision: Union[str, Sequence[str], None] = '2912e5f2faa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractor', sa.Column('headquarters', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contractor', 'headquarters')
    # ### end Alembic commands ###
