"""Add content and content_type to ProjectDocument

Revision ID: ee98b58425f6
Revises: 968d3dc890c0
Create Date: 2026-01-30 17:42:24.616306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee98b58425f6'
down_revision: Union[str, Sequence[str], None] = '968d3dc890c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectdocument', sa.Column('content', sa.LargeBinary(), nullable=True))
    op.add_column('projectdocument', sa.Column('content_type', sa.String(length=255), nullable=True))
    op.alter_column('projectdocument', 'storage_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projectdocument', 'storage_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('projectdocument', 'content_type')
    op.drop_column('projectdocument', 'content')
    # ### end Alembic commands ###
